/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.26
 * Generated at: 2022-11-10 07:08:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class rentupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar", Long.valueOf(1667044410785L));
    _jspx_dependants.put("jar:file:/C:/JobReadyJavaEEOfline/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HomeRenting/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar!/META-INF/c-1_2.tld", Long.valueOf(1649412498000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>HomeRenting Register Form</title>\r\n");
      out.write("<!-- CDN-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/school.ico\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<!--     <form action=\"house\" method=\"post\" class=\"form-horizontal\" role=\"form\"> -->\r\n");
      out.write("		<form action=\"rent\" method=\"post\" class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("\r\n");
      out.write("			<h2 class=\"text-center\">Rent Update</h2>\r\n");
      out.write("			<h3>ID: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.id }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("			<input type=\"hidden\" name=\"mode\" value=\"SUBMIT\" /> <input\r\n");
      out.write("				type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"username\" class=\"form-label\">Username</label> <input\r\n");
      out.write("					type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"username\" readonly=\"readonly\"\r\n");
      out.write("					name=\"username\" class=\"form-control\" autofocus>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"address\" class=\"form-label\">Address</label> <input\r\n");
      out.write("					type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.address}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"address\"\r\n");
      out.write("					readonly=\"readonly\" name=\"address\" class=\"form-control\" autofocus>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"rentPrice\" class=\"form-label\">Rent Price</label> <input\r\n");
      out.write("					type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.rentPrice}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"rentPrice\"\r\n");
      out.write("					readonly=\"readonly\" name=\"rentPrice\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"bedRoom\" class=\"form-label\">Bed Room</label> <input\r\n");
      out.write("					type=\"number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.bedRoom}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"bedRoom\"\r\n");
      out.write("					readonly=\"readonly\" name=\"bedRoom\" class=\"form-control\" autofocus>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"kitchen\" class=\"form-label\">Kitchen</label> <input\r\n");
      out.write("					type=\"number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.kitchen}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"kitchen\"\r\n");
      out.write("					readonly=\"readonly\" name=\"kitchen\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"bathRoom\" class=\"form-label\">Bath Room</label> <input\r\n");
      out.write("					type=\"number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${house.bathRoom}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"bathRoom\"\r\n");
      out.write("					readonly=\"readonly\" name=\"bathRoom\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<div class=\"col-sm-9 col-sm-offset-3\">\r\n");
      out.write("					<span class=\"help-block\">*Required fields</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-primary btn-block\">Submit</button>\r\n");
      out.write("			<button type=\"reset\" class=\"btn btn-danger btn-block\">Reset</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- ./container -->\r\n");
      out.write("\r\n");
      out.write("	<!--         <div class=\"mb-3\"> -->\r\n");
      out.write("	<!--             <label class=\"form-label\">Vaccancy</label> -->\r\n");
      out.write("	<!--             <div class=\"col-sm-6\"> -->\r\n");
      out.write("	<!--                 <div class=\"row\"> -->\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--                  <div class=\"col-sm-4\"> -->\r\n");
      out.write("	<!--                         <label class=\"radio-inline\"> -->\r\n");
      out.write("	<!--                             <input type=\"radio\" id=\"vaccancy\" name=\"vaccancy\" value=\"true\" checked=\"checked\" >Yes -->\r\n");
      out.write("	<!--                         </label> -->\r\n");
      out.write("	<!--                     </div> -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<!--                  <div class=\"col-sm-4\"> -->\r\n");
      out.write("	<!--                         <label class=\"radio-inline\"> -->\r\n");
      out.write("	<!--                             <input type=\"radio\" id=\"vaccancy\" name=\"vaccancy\" value=\"true\">Yes -->\r\n");
      out.write("	<!--                         </label> -->\r\n");
      out.write("	<!--                     </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--                 </div> -->\r\n");
      out.write("	<!--             </div> -->\r\n");
      out.write("	<!--         </div> /.form-group -->\r\n");
      out.write("	<!--         <div class=\"mb-3\"> -->\r\n");
      out.write("	<!--             <div class=\"col-sm-9 col-sm-offset-3\"> -->\r\n");
      out.write("	<!--                 <span class=\"help-block\">*Required fields</span> -->\r\n");
      out.write("	<!--             </div> -->\r\n");
      out.write("	<!--         </div> -->\r\n");
      out.write("	<!--         <button type=\"submit\" class=\"btn btn-primary btn-block\">Submit</button> -->\r\n");
      out.write("	<!--          <button type=\"reset\" class=\"btn btn-danger btn-block\">Reset</button> -->\r\n");
      out.write("	<!--     </form> /form -->\r\n");
      out.write("	<!-- </div> ./container -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap core JS-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Core theme JS-->\r\n");
      out.write("	<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
